name: Release GoFiberCLI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # Needed for creating releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # Specify your Go version

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/${{ github.event.repository.name }}-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o build/${{ github.event.repository.name }}-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o build/${{ github.event.repository.name }}-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o build/${{ github.event.repository.name }}-darwin-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*
          generate_release_notes: true
